name: Generate Filter Rules

on:
    push:
        branches: [ master ]
    schedule:
        - cron: '0 0 * * *'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Remove existing rules
              shell: bash
              run: |
                    if [ -d src/rules ]; then
                        rm -rf src/rules
                    fi
            - name: Generate rules
              run: bun run src/index.ts

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5
              with:
                  commit-message: Update filter rules
                  title: '[Automated] Update Thunderbird Filter Rules'
                  body: |
                      Automated update of Thunderbird filter rules
                      - Generated using latest spam patterns
                      - Please review the changes before merging
                  branch: update-filter-rules
                  delete-branch: true
                  labels: |
                      automated
                      spam-filters
